-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Rattling Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { },
}
itemBases["Stoic Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Discipline",
	implicitModTypes = { },
	req = { int = 12, },
}
itemBases["Lupine Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { int = 24, },
}
itemBases["Omen Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Malice",
	implicitModTypes = { },
	req = { str = 12, int = 25, },
}
itemBases["Ochre Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { int = 40, },
}
itemBases["Shrine Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Fire",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
itemBases["Shrine Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Ice",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
itemBases["Shrine Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Lightning",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
itemBases["Devouring Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { int = 60, },
}
itemBases["Clasped Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Heart of Ice",
	implicitModTypes = { },
	req = { int = 65, },
}
itemBases["Devotional Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { str = 26, int = 63, },
}
itemBases["Wrath Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Fulmination",
	implicitModTypes = { },
	req = { int = 87, },
}
itemBases["Aromatic Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { int = 92, },
}
itemBases["Pious Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { int = 102, },
}
itemBases["Hallowed Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Skeletal Warrior Minion",
	implicitModTypes = { },
	req = { int = 114, },
}

itemBases["Shrine Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Fire",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
itemBases["Shrine Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Ice",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
itemBases["Shrine Sceptre"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	hidden = true,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Lightning",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}

itemBases["Shrine Sceptre (Purity of Fire)"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Fire",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
itemBases["Shrine Sceptre (Purity of Cold)"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Ice",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
itemBases["Shrine Sceptre (Purity of Lighting)"] = {
	type = "Sceptre",
	quality = 20,
	spirit = 100,
	socketLimit = 3,
	tags = { default = true, onehand = true, sceptre = true, },
	implicit = "Grants Skill: Level (1-20) Purity of Lightning",
	implicitModTypes = { },
	req = { str = 17, int = 38, },
}
